/* VINA-SUPERVISION API BRIDGE: giữ nguyên UI + localStorage offline cache, đồng bộ PostgreSQL khi online. */
const VINA_API='http://localhost:8000';
async function vinaHealth(){try{let r=await fetch(VINA_API+'/health',{cache:'no-store'});return r.ok?await r.json():null}catch(e){return null}}
function vinaUUID(v){return typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f-]{27,}$/i.test(v)}
async function vinaPush(){if(!navigator.onLine)return;const map={projects:'project',logs:'daily_log',issues:'issue',docs:'document',people:'person',audit:'audit',sync:'sync'},records=[];for(const [k,t] of Object.entries(map))for(const x of(db[k]||[]))if(x&&vinaUUID(x.id))records.push({entity_type:t,entity_id:x.id,payload:x});if(!records.length)return;try{let r=await fetch(VINA_API+'/api/v1/sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({records})});if(r.ok){window.__vinaDB='ONLINE+DATABASE';updateNet()}}catch(e){window.__vinaDB='OFFLINE/CACHE';updateNet()}}
async function vinaPull(){if(!navigator.onLine)return;try{let r=await fetch(VINA_API+'/api/v1/records',{cache:'no-store'});if(!r.ok)return;let rows=await r.json(),map={project:'projects',daily_log:'logs',issue:'issues',document:'docs',person:'people',audit:'audit',sync:'sync'},changed=false;for(const row of rows){let k=map[row.entity_type];if(!k)continue;db[k]=db[k]||[];let i=db[k].findIndex(x=>x.id===row.entity_id);if(i<0){db[k].push(row.payload);changed=true}else{let a=new Date(db[k][i].updatedAt||db[k][i].createdAt||0).getTime(),b=new Date(row.updated_at||0).getTime();if(b>a){db[k][i]=row.payload;changed=true}}}if(changed)localStorage.setItem(KEY,JSON.stringify(db));window.__vinaDB='ONLINE+DATABASE';updateNet()}catch(e){}}
const _vinaSave=save;save=function(){_vinaSave();vinaPush()};
window.addEventListener('online',async()=>{await vinaPull();await vinaPush();renderAll()});
const _vinaNet=updateNet;updateNet=function(){_vinaNet();let e=document.getElementById('net');if(e&&window.__vinaDB==='ONLINE+DATABASE')e.textContent='● ONLINE + DATABASE'};
(async()=>{let h=await vinaHealth();if(h&&h.database==='ok'){window.__vinaDB='ONLINE+DATABASE';await vinaPull();await vinaPush()}else window.__vinaDB='OFFLINE/CACHE';updateNet()})();
